### PR TITLE
Add custom nlp for CorefTrainer

### PR DESCRIPTION
**Pull request by wannaphong**
Add custom nlp for CorefTrainer to train more language.

### CODE REVIEW

**Comment by shon-otmazgin** [comment]
Hi
The trainer must have nlp object, and the use of tokenized test in predict function is only possible for inference, can you change the if/else statements accordingly?

**Comment by wannaphong** [comment]
> Hi The trainer must have nlp object, and the use of tokenized text in predict function is only possible for inference, can you change the if/else statements accordingly?

OK. I was change the if/else statements.

**Comment by shon-otmazgin** [comment]
Thanks!. lastly, also needs to update the README in the train section since you added a new parameter to the trainer class

**Review by shon-otmazgin — APPROVED** [review]

**Comment by shon-otmazgin** [comment]
@wannaphong I just released version 2.1.6 thanks.

**Pull request merged**
