### PR TITLE
prevent auto-installing wandb

### LINKED ISSUE #26: prevent install wandb if not for training
for users that dont want to train the coref model themselves, the automatic install of wandb is redundant. especially  that this package is cluttering the logs if it is not configured

### PR DESCRIPTION
**Pull request by aryehgigi**
Fixes #26

### CODE REVIEW

**Comment by aryehgigi** [comment]
@shon-otmazgin @ariecattan wdyt?
this is ready for review

**Comment by shon-otmazgin** [comment]
@aryehgigi very nice and clean solution. before approval, did you test it and it worked?

**Review by shon-otmazgin — APPROVED** [review]

**Comment by aryehgigi** [comment]
actually i didnt check it. and now that i do i see that it does not install wandb unless specified - as expected.
but then `from fastcoref import FCoref` throws an error cause `__init__.py` imports both `modeling` stuff and `training` stuff.
we can remove it from the init, but then users would need to import like this:
`from fastcoref.modeling import FCoref` which is fine, but will break backward compatability.

so dont merge this yet as i dont have a solution to not break backward compatibility but in the same time not import `training`. if you find something lmk?

**Comment by aryehgigi** [comment]
ok @shon-otmazgin i found a solution that doesnt break backward compatability and doesnt import wandb if the trainer is not used.
the only disadvantage is that it is a bit ugly code-wise. but personally i think its fine.. wdyt?
(i obviously tested it now)

**Pull request merged**
